// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDVxK-Y3unQs4EbMlt_Ol2KLKkVwLuhn0',
    appId: '1:903939838515:web:78cec5b51e362b80f04946',
    messagingSenderId: '903939838515',
    projectId: 'edu-projects-8ef5c',
    authDomain: 'edu-projects-8ef5c.firebaseapp.com',
    storageBucket: 'edu-projects-8ef5c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgI2bv1EFbFxB_nhdsOII0sFjfQTwUmkg',
    appId: '1:903939838515:android:78bdbe7fe7e5e287f04946',
    messagingSenderId: '903939838515',
    projectId: 'edu-projects-8ef5c',
    storageBucket: 'edu-projects-8ef5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE3zlploLG0_LQD-zO2aFP5N2cCHLWwYA',
    appId: '1:903939838515:ios:bc1234acc1e32666f04946',
    messagingSenderId: '903939838515',
    projectId: 'edu-projects-8ef5c',
    storageBucket: 'edu-projects-8ef5c.firebasestorage.app',
    iosBundleId: 'com.example.studentManager',
  );
}
